[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://dsaproblem.netlify.app/*"
  to = "https://dsa.priyan.online/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://dsaproblem.netlify.app/*"
  to = "https://dsa.priyan.online/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://backend.priyan.online/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
